version: "2"

services:
  influxdb:
    image: dockerproxy-cwfr1.rd.francetelecom.fr/influxdb
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"
  chronograf:
    image: dockerproxy-cwfr1.rd.francetelecom.fr/chronograf
    volumes:
      - ./data/chronograf:/var/lib/chronograf
    ports:
      - "8888:8888"
    links:
      - influxdb